sudo: required
services:
  - docker

  before_install:
    - docker build -t rajeshgupta21/react-test -f ./client/Dockerfile.dev ./client

  script:
    - docker run rajeshgupta21/react-test npm test -- --coverage

  after_success:
    - docker build -t rajeshgupta21/multi-client ./client
    - docker build -t rajeshgupta21/multi-nginx ./nginx
    - docker build -t rajeshgupta21/multi-server ./server
    - docker build -t rajeshgupta21/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push rajeshgupta21/multi-client
    - docker push rajeshgupta21/multi-nginx
    - docker push rajeshgupta21/multi-server
    - docker push rajeshgupta21/multi-worker
    
